title: SonoranCactusContracting.com
email: greg@sonorancactuscontracting.com
description: >-
  Sonoran Cactus Contracting is a general remodel residential & commercial 
  contractor that can meet all of your needs.
baseurl: ''
url: 'https://localhost'

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
